### ISSUE TITLE
Email sender always sends the same image 

### ISSUE THREAD

**Issue by benhylak** [CS3733TeamBeta/Faulkner.Kiosk#34]
This is the image that is always sent regardlesss of the path (and there's not even a straight line like that anywhere on the map)

![noname-1](https://cloud.githubusercontent.com/assets/19956321/23187702/d9173b08-f859-11e6-9b8e-fd2f5d31a6fe.png)

**Comment by benhylak** [comment]
Issue must be resolved for pull request of #42

please checkout this branch, clean git+gradle, build with gradle, click a node on the map to run A*, and then use the directions panel to send an email to yourself. IF you also get this image. Please comment whether or not you get the same image. ASAP please

**Comment by benhylak** [comment]
Everyone assigned should have this done within 15 minutes.

**Comment by sophiagudenrath** [comment]
I also received the same image but the directions were accurate to the node I clicked

**Comment by pjpolley** [comment]
There's actually a bunch of problems with this code. First off, we're displaying incorrect backgrounds. Second, we don't check for the correct image to send (which is why you keep getting the wrong one), and third, the constant that is used to scale everything in the rendering process only works for one floor. we either need constants for all floormaps with different dimensions to render the nodes and edges in the right places or a method to generate a constant on the fly.

**Comment by benhylak** [comment]
Mark this issue off when done pleasE!@!@#!@$#
